### PR TITLE
Development

### PR DESCRIPTION
**Pull request by vids12**
Live Demo: https://kalapottery.netlify.app/
Feel free to comment your views and thoughts.

This PR got merged by mistake. So, I have made a new PR. The Link for the new PR is: #3

### CODE REVIEW

**Comment by panchami6** [comment]
Hi Vidushi, 
Your e-Commerce looks good and the code is clean too.

I found some issues: When I remove one cart item, the cart gets empty. Same is for wishlist. 
I have a suggestion: In wishlist page, there is space below the footer when the wishlist is empty. You can either make sticky footer or make bottom: 0.

**Comment by vids12** [comment]
Reopening the pull request

**Comment by vids12** [comment]
> Hi Vidushi,
> Your e-Commerce looks good and the code is clean too.
> 
> I found some issues: When I remove one cart item, the cart gets empty. Same is for wishlist.
> I have a suggestion: In wishlist page, there is space below the footer when the wishlist is empty. You can either make sticky footer or make bottom: 0.

Will surely work on it.

**Comment by SauravKumar-max** [comment]
Hi @vids12, your app functionalities are working really well.

But I found an issue which is that if I refresh any page other than the landing page it shows page not found by Netlify to fix that you have to create a  `_redirects` file inside the public folder with ``  /*    /index.html  200 `` code in it, this will solve the problem.

**Pull request merged**
